// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD00NsOpqejs-TORsPp_QFiCPUwwexU0ME',
    appId: '1:812906321465:web:940a5dc17eccab0aeadfe8',
    messagingSenderId: '812906321465',
    projectId: 'reddit-448f0',
    authDomain: 'reddit-448f0.firebaseapp.com',
    storageBucket: 'reddit-448f0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXgofwb56VJks147MnoBnCPInirhm8VXk',
    appId: '1:812906321465:android:65a52c6a47c01ddeeadfe8',
    messagingSenderId: '812906321465',
    projectId: 'reddit-448f0',
    storageBucket: 'reddit-448f0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLnPzBW0hOiCompHb4nsYUCPF4RgVlo30',
    appId: '1:812906321465:ios:995ba42eead6843aeadfe8',
    messagingSenderId: '812906321465',
    projectId: 'reddit-448f0',
    storageBucket: 'reddit-448f0.appspot.com',
    iosBundleId: 'dev.hayohtee.reddit',
  );
}
